name: Pipeline-CD
on:
  push:
    branches: [ production ]
jobs:
  cd:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - uses: actions/checkout@v2
      
      - name: Deploy Over SSH
        uses: LuisEnMarroquin/setup-ssh-action@v3.0.0
        with:
          ORIGIN: ${{ secrets.HOST }}
          SSHKEY: ${{ secrets.SSH_PRIVATE_KEY }}
          NAME: production
          PORT: ${{ secrets.PORT }}
          USER: ${{ secrets.USER }}
      - script: ls
